<?php
// $Id$

/**
 * Implementation of hook_nodeapi().
 */
function kkblyd_admin_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($op == 'presave' && $node->type == 'sound_article') {

    // Set publish date to noon of the selected date if later than today.
    if ($node->field_publish_date[0]['value'] > date('Y-m-d', $_SERVER['REQUEST_TIME']) . 'T00:00:00') {
      $node->publish_on = strtotime($node->field_publish_date[0]['value']) + 12 * 3600;
    }

    // Set publish date to noon +7 days of the selected date.
    $node->unpublish_on = strtotime($node->field_publish_date[0]['value']) + 12 * 3600 + 7 * 86400;
  }
}

/**
 * Implementation of hook_views_api() {
 */
function kkblyd_admin_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
 * Implementation of hook_form_alter().
 *
 * Modifications for the sound article editing form.
 */
function kkblyd_admin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'sound_article_node_form') {
    drupal_add_js(drupal_get_path('module', 'kkblyd_admin') . '/kkblyd_admin.node_form.js');
    $form['promote'] = array(
      '#type' => 'checkbox',
      '#title' => t('Include in daily news'),
      '#default_value' => 1,
      '#weight' => -3,
    );
    unset($form['options']['promote']);
    // Hide the scheduler-settings, since we set them programmatically.
    $form['scheduler_settings']['#type'] = '';
    $form['scheduler_settings']['publish_on']['#type'] = 'value';
    $form['scheduler_settings']['publish_on']['#value'] = '';
    $form['scheduler_settings']['unpublish_on']['#type'] = 'value';
    $form['scheduler_settings']['unpublish_on']['#value'] = '';

    // Add our own submit handler to prevent redirect to node view.
    $form['buttons']['submit']['#submit'][] = 'kkblyd_admin_form_sound_article_submit';
    // Hide the preview button, since it's useless for this node type.
    unset($form['buttons']['preview']);
  }
}

/**
 * Submit handler for the sound article editing form.
 */
function kkblyd_admin_form_sound_article_submit($form, &$form_state) {
  if (isset($form['nid']['#value']) && !empty($form['nid']['#value'])) {
    $form_state['redirect'] = '<front>';
  }
  else {
    $form_state['redirect'] = 'node/add/sound-article';
  }
}


