<?php
// $Id$

/**
 * Implementation of hook_views_api() {
 */
function kkblyd_admin_views_api() {
  return array(
    'api' => 2.0,
  );
}
/**
 * Implementation of hook_form_FORM_ID_alter().
 *
 * Modifications for the sound article editing form.
 */
function kkblyd_admin_form_sound_article_node_form_alter(&$form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'kkblyd_admin') . '/kkblyd_admin.node_form.js');
}

