<?php
// $Id$

/**
 * @file
 * Implementation of Drupal core hooks.
 *
 */

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function kkblyd_custom_form_contact_mail_page_alter(&$form, $form_state) {
  $form['subject']['#type'] = 'radios';
  $form['subject']['#options'] = array(
    'soundbooks' => t('Question about sound books and other publications'),
    'production' => t('Question about reading and sound production'),
    'soundnews' => t('Question about sound news'),
    'development' => t('Question about development projekts'),
    'other' => t('Other questions'),
  );

  $form['phone'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone'),
    '#description' => t('Optionally enter your phone number'),
  );

  $form['company'] = array(
    '#type' => 'textfield',
    '#title' => t('Company'),
    '#description' => t('Optionally enter your company'),
  );

  // Set weights to get the order we want.
  $form['subject']['#weight'] = 2;
  $form['message']['#weight'] = 2;
  $form['submit']['#weight'] = 2;
  $form['copy']['#weight'] = 2;
}